{
	"version": 1606962377,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/carro-sheet0.png",
		"images/blococarro-sheet0.png",
		"images/limiteslaterais-sheet0.png",
		"images/cone-sheet0.png",
		"images/bola-sheet0.png",
		"images/caixa-sheet0.png",
		"images/botãoiniciar-sheet0.png",
		"images/pista-sheet0.png",
		"images/gameover-sheet0.png",
		"images/tiledbackground.png",
		"images/welcome-sheet0.png",
		"images/parabens-sheet0.png",
		"images/intro-sheet0.png",
		"images/intro-sheet1.png",
		"images/objetos-sheet0.png",
		"images/sprite-sheet0.png",
		"media/barulho   carro acelerando.ogg",
		"media/clicking mouse pointer + sound (green screen).ogg",
		"media/carro andando.ogg",
		"media/mixkit-arcade-retro-changing-tab-206.m4a",
		"media/mixkit-arcade-space-shooter-dead-notification-272.m4a",
		"media/mixkit-arcade-space-shooter-dead-notification-272.ogg",
		"media/mixkit-game-level-completed-2059.m4a",
		"media/mixkit-game-level-completed-2059.ogg",
		"media/mixkit-retro-game-over-1947.m4a",
		"media/mixkit-retro-game-over-1947.ogg",
		"media/anyconv.com__y2mate.com - twenty one pilots - nico and the niners (official video).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}